import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar/Navbar'
import HomeLayout from '../components/layout/HomeLayout'
import { Flex } from '@chakra-ui/react'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main>
        <Flex       justifyContent="center"
      alignItems="center" direction="column">

          <HomeLayout/>

        </Flex>
      </main>
    </div>
  )
}
